// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Maui.Storage;

namespace Diploma_cs
{
    public partial class MainComputingModule
    {
        /// <summary>
        /// model input class for MainComputingModule.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"AvgConsumedWeek")]
            public float AvgConsumedWeek { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"AvgBoughtPacks")]
            public float AvgBoughtPacks { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"BoughtSum")]
            public float BoughtSum { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"ReduceBy")]
            public float ReduceBy { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MainComputingModule.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"AvgConsumedWeek")]
            public float AvgConsumedWeek { get; set; }

            [ColumnName(@"AvgBoughtPacks")]
            public float AvgBoughtPacks { get; set; }

            [ColumnName(@"BoughtSum")]
            public float BoughtSum { get; set; }

            [ColumnName(@"ReduceBy")]
            public float ReduceBy { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        // Note: we no longer rely on a file system path; we load the model from the app package.
        private const string AppPackageModelPath = "MachineLearning/MainComputingModule.mlnet";

        // Cache the loaded ITransformer (thread-safe).
        private static readonly Lazy<ITransformer> LoadedModel = new Lazy<ITransformer>(() =>
        {
            var mlContext = new MLContext();
            try
            {
                // Open model stream from the MAUI app package (works on Android/iOS/Windows).
                using var stream = FileSystem.OpenAppPackageFileAsync(AppPackageModelPath).GetAwaiter().GetResult();
                return mlContext.Model.Load(stream, out var _);
            }
            catch (Exception ex)
            {
                // Wrap to provide clearer file-not-found info at call site.
                throw new FileNotFoundException($"Could not load ML model '{AppPackageModelPath}' from app package.", ex);
            }
        }, true);

        /// <summary>
        /// Create a PredictionEngine for a single thread/use. PredictionEngine is not thread-safe.
        /// </summary>
        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            var mlContext = new MLContext();
            var model = LoadedModel.Value;
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(model);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            // Create a fresh PredictionEngine per call (safe for concurrent usage).
            using var engine = CreatePredictionEngine();
            return engine.Predict(input);
        }
    }
}
